permalink: pretty

title: Meritage Homes Static Site
url: http://www.meritagehomes.com
baseurl: ./

sass:
  sass_dir: _scss
  sourcemap: true
  style: expanded

port: 8080

exclude: [
  'node_modules',
  'gulpfile.js',
  '.sass-cache',
  '_assets',
  'Gemfile',
  'Gemfile.lock',
  'package.json'
]